name: Backend Deployment

on:
  push:
    paths:
      - "lambda/**"
jobs:
  backend:
    runs-on: ubuntu-latest
    name: Backend Deployment
    environment: PROD
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - run: sudo apt-get install -y zip
      - name: Zip Lambda Functions
        working-directory: lambda
        run: zip lambda_function.zip lambda_function.py
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Update Lambda Function
        working-directory: lambda
        run: |
          aws lambda update-function-code --function-name user_count_lambda \
          --zip-file fileb://lambda_function.zip