name: Frontend Deployment

on:
  push:
    paths:
      - "website/**"
  workflow_dispatch:
jobs:
  check_bucket:
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_VAR_s3_bucket_name: ${{ vars.S3_BUCKET_NAME }}
    outputs:
      bucket_exists: ${{ steps.check.outputs.exists }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - id: check
        run: |
          if aws s3api head-bucket --bucket your-frontend-bucket 2>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  deploy_frontend:
    needs: check_bucket
    runs-on: ubuntu-latest
    if: needs.check_bucket.outputs.bucket_exists == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Upload website to S3
        run: aws s3 sync website/ s3://${{ vars.S3_BUCKET_NAME }} --delete

  trigger_infra:
    needs: check_bucket
    runs-on: ubuntu-latest
    if: needs.check_bucket.outputs.bucket_exists == 'false'
    steps:
      - name: Trigger infrastructure workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: infrastructure.yml
          token: ${{ secrets.GITHUB_TOKEN }}