name: Infrastructure cleanup

on:
  workflow_dispatch
jobs:
  infrastructure:
    runs-on: ubuntu-latest
    name: Deploy Infrastructure
    environment: PROD
    env:
      TF_VAR_region: ${{ vars.AWS_REGION }}
      TF_VAR_user_account: ${{ vars.AWS_USER_ACCOUNT }}
      TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
      TF_VAR_dynamodb_table_name: ${{ vars.DYNAMODB_TABLE_NAME }}
      TF_VAR_origin_name: ${{ vars.ORIGIN_NAME }}
      TF_VAR_s3_bucket_name: ${{ vars.S3_BUCKET_NAME }}
      TF_VAR_api_gateway_name: ${{ vars.API_GATEWAY_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: echo "Deploying Infrastructure"
      - name: Terraform Init
        run: terraform init
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
      